# Generated by Django 3.2.17 on 2023-04-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='img/', verbose_name='イラスト'),
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
